modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/SrRapero720/waterframes/issues"
logoFile="pack.png"
license="All rights reserved"

[[mods]]
	modId="waterframes"
	version="${file.jarVersion}"
	displayName="WATERFrAMES"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/waterframes"
	credits="CreativeMD: Original author"
	authors="SrRapero720: Proyect Owner --- CoolDCB: Porting help"
	description='''Show to all your friends your dank memes or rickroll
	all the server using the official urlfrom youtube.
	How more you need to know? is a mod to show media
	in your game has a paint, tv. JUST DISPLAY IT

	#ShowItIngame
'''


[[dependencies.waterframes]]
	modId = "forge"
	mandatory = true
	versionRange = "[40,)"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.waterframes]]
	modId="creativecore"
	mandatory=true
	ordering="NONE"
	side="BOTH"
	versionRange="[2.6,)"

[[dependencies.waterframes]]
	modId="watermedia"
	mandatory=true
	ordering="NONE"
	side="CLIENT"
	versionRange="[0.1,)"

#[[dependencies.waterframes]]
#    modId="watercore"
#    mandatory=false
#    ordering="NONE"
#    side="BOTH"
#    versionRange="[1.3,)"