modLoader="javafml"
loaderVersion="${fgloaderrange}"
issueTrackerURL="https://github.com/SrRapero720/waterframes/issues"
logoFile="pack.png"
license="${modlicense}"

[[mods]]
	modId="${modid}"
	version="${modversion}"
	displayName="${modname}"
	displayTest="MATCH_VERSION"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/waterframes"
	credits="${modcredits}"
	authors="${modauthor}"
	logoFile="pack.png"
	side="BOTH"
	description='''${mod_description}'''


[[dependencies.${mod_id}]]
	modId="forge"
	mandatory=true
	versionRange="${fgrange}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="creativecore"
	mandatory=true
	ordering="AFTER"
	side="BOTH"
	versionRange="${creativecorerange}"

[[dependencies.waterframes]]
	modId="watermedia"
	mandatory=true
	ordering="AFTER"
	side="CLIENT"
	versionRange="${watermediarange}"