modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="https://github.com/SrRapero720/waterframes/issues"
logoFile="pack.png"
license="${mod_license}"

[[mods]]
	modId="${mod_id}"
	version="${mod_version}"
	displayName="${mod_name}"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/waterframes"
	credits="Special thanks to CoolDCB and CreativeMD"
	authors="SrRapero720"
	logoFile="pack.png"
	description='''${mod_description}'''


[[dependencies.${mod_id}]]
	modId = "forge"
	mandatory = true
	versionRange = "${loader_version_range}"
	ordering = "NONE"
	side = "BOTH"

[[dependencies.${mod_id}]]
	modId="creativecore"
	mandatory=true
	ordering="NONE"
	side="BOTH"
	versionRange="${creativecore_version_range}"

[[dependencies.waterframes]]
	modId="watermedia"
	mandatory=true
	ordering="AFTER"
	side="CLIENT"
	versionRange="${watermedia_version_range}"

#[[dependencies.waterframes]]
#    modId="watercore"
#    mandatory=false
#    ordering="NONE"
#    side="BOTH"
#    versionRange="[1.3,)"